pipeline {
  agent {
    kubernetes {
      yaml '''
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command: ['sleep']
      args: ['99d']
    - name: git
      image: alpine/git
      command: ['sleep']
      args: ['99d']
'''
    }
  }

  environment {
    ECR_REGISTRY = "<account>.dkr.ecr.us-west-2.amazonaws.com"
    IMAGE_NAME   = "app"
    IMAGE_TAG    = "v1.0.${BUILD_NUMBER}"

    COMMIT_EMAIL = "jenkins@localhost"
    COMMIT_NAME  = "jenkins"
  }

  stages {
    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \
              --context `pwd` \
              --dockerfile `pwd`/django/Dockerfile \
              --destination=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
              --cache=true \
              --insecure \
              --skip-tls-verify
          '''
        }
      }
    }

    stage('Update Chart Tag in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh '''
              git config --global user.email "$COMMIT_EMAIL"
              git config --global user.name "$COMMIT_NAME"
              git clone https://$GIT_USERNAME:$GIT_PAT@github.com/REPO_OWNER/REPO_NAME.git repo
              cd repo
              sed -i "s#^\\s*repository:.*#    repository: '$ECR_REGISTRY/$IMAGE_NAME'#" lesson-8-9/charts/django-app/values.yaml
              sed -i "s#^\\s*tag:.*#    tag: '$IMAGE_TAG'#" lesson-8-9/charts/django-app/values.yaml
              git add lesson-8-9/charts/django-app/values.yaml
              git commit -m "Update image to $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
              git push origin main
            '''
          }
        }
      }
    }
  }
}


